### ISSUE TITLE
Práctica 6

### ISSUE THREAD

**Issue by KarenGarciaGarcia** [SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-proyecto-equipo-evelin#1]
[Reporte de practica6.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-proyecto-equipo-evelin/files/12839403/Reporte.de.practica6.pdf)

**Comment by isaireyesp1** [comment]
Portada : 25
Procedimiento : 25
Figuras, ilustraciones y fotografías. : 25
Resultados y conclusiones : 25
calificación : 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
